---
name: PSScriptAnalyzer
on:
  push:
    branches: [ "main" ]
    paths:
      - '**.ps1'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  scan:
    name: PSScriptAnalyzer
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install PSScriptAnalyzer
      shell: powershell
      run: Install-Module -Name PSScriptAnalyzer -Force

    - name: Run PSScriptAnalyzer
      shell: powershell
      run: |
        $files = Get-ChildItem . -Include *.ps1,*.psm1,*.psd1 -Recurse
        ./.github/scripts/Invoke-PSSA.ps1 -Files $files
